version: '3.7'
services:
  ## Image runtime service
  ## This can be used to add volume mounts or pass environment variables
  ## Todo: make a service which can use the container interactively
  notebook:
    image: bhargav28/jupyter_signal:pyvhr
    container_name: jupyter_notebook
    #build:
    # context: .
    # dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "./Notebooks"
        target: "/home/Notebooks"
      #- "${DATA_MOUNT}:/home/Notebooks"
    tty: true

  openface:
    image: bhargav28/openface
    container_name: openface
 #   build:
  #    context: .
   #   dockerfile: openface/Dockerfile
    #image: openface:latest
    tty: true
    volumes:
      - type: bind
        source: "./Notebooks"
        target: /home/Notebooks
      #- "${DATA_MOUNT}:/home/Notebooks"
    environment:
      DATA_MOUNT: "${DATA_MOUNT}"
    command: ["bash"]


...
